parameters: {}
environment: {}
packages:
    - name: og-parse
      shared: false
      environment: {}
      parameters: {}
      annotations: {}
      functions:
        - name: extract
          binary: false
          main: ""
          runtime: python:default
          web: true
          webSecure: false
          parameters: {}
          environment: 
            OG_USER_AGENT: "TwitterBot"
          annotations: {}
          limits: {}
